spring:
  application:
    name: combat-arena
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/combat-arena
    username: combat-arena-admin
    password: cfbf6b2e-41d6-4a1e-af9a-955082faf1d1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    enabled: true

filesystem:
  userResourcesPath: D:\Development\userresources\

server:
  port: 8080
  tomcat:
    threads:
      max: 25

#logging:
#  config: classpath:logback.xml
#  level:
#    com.combat.arena: debug
#    org.thymeleaf: warn
#    org.thymeleaf.TemplateEngine.TIMER: warn
#    org.springframework.jndi: warn
#    org.org.hibernate: error

#    url: jdbc:postgresql://localhost:5432/combat-arena
#    username: combat-arena-admin
logging:
  level:
    com.combat.arena: debug

#    password: cfbf6b2e-41d6-4a1e-af9a-955082faf1d1