spring:
  application:
    name: fsknso-competition
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    enabled: true